In [1]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.lines as mlines
from ase.io import write, read
import pandas as pd
import umap
import seaborn as sns
from quippy.descriptors import Descriptor
from sklearn.decomposition import PCA
import matplotlib.cm as cm
import matplotlib.colors as mcolors
from matplotlib.colors import LinearSegmentedColormap
import matplotlib as mpl
import chemiscope

plt.style.use('~/plot.mplstyle')
mpl.rcParams['figure.dpi'] = 150
mpl.rcParams['mathtext.default']='regular'

In [3]:
file_train='../../data/datasets/combined-to-Ite6-filtered-Fmag-50-Emax-0-min-Si-1.6-SiH-1.0-train.pkl.gzip'

df=pd.read_pickle(file_train, compression='gzip')

In [4]:
def umap_config(row):
    config=row["config"]
    if config=='cbulk' or config=='SnB':
        umap_config='crystalline'
    elif config=='amorph' or config=='ahighT':
        umap_config='amorphous'
    elif config=='cluster' or config=='sp':
        umap_config='cluster'
    elif config=='metabulk' or config=='high-p':
        umap_config='high-p'
    elif config=='a-surface' or config=='c-surface':
        umap_config='surface'
    elif config=='liq':
        umap_config='liquid'
    elif config=='mol':
        umap_config='molecule'
    else:
        print(config)
    return umap_config

df['umap_config']=df.apply(umap_config, axis=1)

In [5]:
for config in df.umap_config.unique():
    print(config)
    df_tmp=df[df.umap_config==config]
    print(df_tmp.iteration.unique())
    print(len(df_tmp.ase_atoms.values))

    print(f'tot nb atoms {np.sum(df_tmp.nb_atoms)}')
    print(f'Si nb atoms {np.sum(df_tmp.nSi.values)}')
    print(f'H nb atoms {np.sum(df_tmp.nH.values)}')

crystalline
[0 1]
1289
tot nb atoms 54291
Si nb atoms 51296
H nb atoms 2995
amorphous
[0 1 6]
2030
tot nb atoms 279686
Si nb atoms 265453
H nb atoms 14233
liquid
[0 1 2 5 6]
697
tot nb atoms 68965
Si nb atoms 56515
H nb atoms 12450
high-p
[0 4]
717
tot nb atoms 16776
Si nb atoms 16776
H nb atoms 0
molecule
[0 4]
438
tot nb atoms 5484
Si nb atoms 997
H nb atoms 4487
cluster
[2 3 6]
382
tot nb atoms 2458
Si nb atoms 808
H nb atoms 1650
surface
[3]
54
tot nb atoms 5362
Si nb atoms 2812
H nb atoms 2550
