In [4]:
from ase.io import read,write
import numpy as np
import os
from ase.filters import UnitCellFilter
from ase.optimize import BFGS
from ase.filters import Filter
from ase.eos import calculate_eos
import copy
import glob
from pyace import PyACECalculator

In [5]:
potfilename='../../models/SiH-ACE-25.yaml'
acepot = PyACECalculator(potfilename)

In [6]:
names=['SiH2_s3B1d', 'SiH3', 'SiH4', 'Si2H6']

In [7]:
for name in names:
    print(name)
    atoms=read(f'../../data/paper/molecules/{name}/POSCAR')

    atoms.calc=acepot
    dyn = BFGS(atoms)
    dyn.run(fmax=0.0001)
    write(f'../../data/paper/molecules/{name}/{name}_ace_relaxed.xyz', atoms)
    print(atoms.get_all_distances())

SiH2_s3B1d
      Step     Time          Energy          fmax
BFGS:    0 13:32:37       -9.630526        2.375068
BFGS:    1 13:32:37       -9.727943        1.456682


BFGS:    2 13:32:37       -9.819465        0.832556
BFGS:    3 13:32:37       -9.847800        0.849553
BFGS:    4 13:32:37       -9.899590        0.716071
BFGS:    5 13:32:37       -9.932102        0.488620
BFGS:    6 13:32:37       -9.940802        0.102885
BFGS:    7 13:32:37       -9.941167        0.012974
BFGS:    8 13:32:37       -9.941182        0.000135
BFGS:    9 13:32:37       -9.941182        0.000001
[[0.         1.50511983 1.50511983]
 [1.50511983 0.         2.22446388]
 [1.50511983 2.22446388 0.        ]]
SiH3
      Step     Time          Energy          fmax
BFGS:    0 13:32:37      -14.756709        0.373623
BFGS:    1 13:32:37      -14.759443        0.339748
BFGS:    2 13:32:37      -14.774724        0.212117
BFGS:    3 13:32:37      -14.776666        0.139461
BFGS:    4 13:32:37      -14.777964        0.072747
BFGS:    5 13:32:37      -14.778774        0.019295
BFGS:    6 13:32:37      -14.778813        0.004355
BFGS:    7 13:32:37      -14.778814        0.000159
BFGS

In [15]:
### GAP22
from quippy.potential import Potential

In [ ]:
gap22=Potential(param_filename='../../models/GAP22/GAP_Si_H_PRM.xml')

In [ ]:
names=['SiH2_s3B1d', 'SiH3', 'SiH4', 'Si2H6']
for name in names:
    print(name)
    atoms=read(f'../../data/paper/molecules/{name}/POSCAR')

    atoms.calc=gap22
    dyn = BFGS(atoms)
    dyn.run(fmax=0.0001)
    write(f'../../data/paper/molecules/{name}/{name}_gap22_relaxed.xyz', atoms)
    print(atoms.get_all_distances())

SiH2_s3B1d
      Step     Time          Energy          fmax
BFGS:    0 22:26:21     -131.694989        1.247082
BFGS:    1 22:26:21     -131.744131        1.100999
BFGS:    2 22:26:21     -131.925156        0.678335
BFGS:    3 22:26:21     -131.945052        0.411885
BFGS:    4 22:26:21     -131.950228        0.244468
BFGS:    5 22:26:21     -131.952945        0.026869
BFGS:    6 22:26:21     -131.953020        0.003596
BFGS:    7 22:26:21     -131.953021        0.000331
BFGS:    8 22:26:21     -131.953021        0.000014
[[0.         1.4827513  1.4827513 ]
 [1.4827513  0.         2.26115194]
 [1.4827513  2.26115194 0.        ]]
SiH3
      Step     Time          Energy          fmax
BFGS:    0 22:26:21     -147.150609        1.281625
BFGS:    1 22:26:21     -147.216057        0.957484
BFGS:    2 22:26:21     -147.320815        0.895293
BFGS:    3 22:26:21     -147.336901        0.798442
BFGS:    4 22:26:21     -147.371777        0.411758
BFGS:    5 22:26:21     -147.380875        0.07